name: Generate Doxygen documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake doxygen graphviz \
          libasound2-dev libjack-jackd2-dev \
          ladspa-sdk \
          libcurl4-openssl-dev  \
          libfreetype-dev libfontconfig1-dev \
          libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
          libwebkit2gtk-4.1-dev \
          libglu1-mesa-dev mesa-common-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/Gain/build -S ${{github.workspace}}/Gain -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Docs generation
        run: cmake --build ${{github.workspace}}/build -S ${{github.workspace}}/Gain --config ${{env.BUILD_TYPE}} --target doc
